#!/bin/bash
echo "Starting enhanced build process..."

# Print environment for debugging (no sensitive data)
echo "Node version: $(node -v)"
echo "NPM version: $(npm -v)"
echo "AI_PROVIDER: $AI_PROVIDER"

# Clean any previous build artifacts
rm -rf dist api
echo "Cleaned previous build artifacts"

# Check for stale files that might be causing issues
find . -name "*.js" -path "./src/*" -type f | xargs rm -f
echo "Removed any stale JS files from src directory"

# Install dependencies
npm ci
echo "Dependencies installed"

# Run TypeScript compilation with verbose output
echo "Starting TypeScript compilation..."
npx tsc --listEmittedFiles
echo "TypeScript compilation complete"

# Create API directory and index file
mkdir -p api
echo "// Generated by build process at $(date)" > api/index.js
echo "const app = require('../dist/server');" >> api/index.js
echo "module.exports = app;" >> api/index.js
echo "Created API files"

# Verify the built files
echo "Verifying build..."
if [ -f "dist/server.js" ]; then
  echo "✅ dist/server.js exists"
else
  echo "❌ dist/server.js is missing!"
  exit 1
fi

if [ -f "dist/utils/textProcessing.js" ]; then
  echo "✅ dist/utils/textProcessing.js exists"
  # Check if the file contains direct OpenAI import
  if grep -q "openai" "dist/utils/textProcessing.js"; then
    echo "⚠️ Warning: dist/utils/textProcessing.js contains direct OpenAI references!"
    # Uncomment to fail the build if this happens
    # exit 1
  else
    echo "✅ textProcessing.js has no direct OpenAI imports"
  fi
fi

echo "Build completed successfully!" 